#!/usr/bin/env python3
"""Refresh the autogenerated section in AGENTS.md.

Run this whenever you change function signatures, add/remove modules,
or rename top-level constants. The line numbers in AGENTS.md were
removed on purpose — agents should grep for the symbol name. This
script just keeps the per-module symbol catalogue current.

Usage:
    python3 scripts/refresh_agents_md.py
    python3 scripts/refresh_agents_md.py --check   # exit 1 if drifted
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
AGENTS_MD = PROJECT_ROOT / "AGENTS.md"

# Files we summarise. Order matters — entries appear in this order.
# The collector is a package; we index its submodules separately so the
# module map mirrors the on-disk layout an agent should grep through.
PIPELINE_FILES: tuple[Path, ...] = (
    PROJECT_ROOT / "src/news_digest/pipeline/collector/__init__.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/core.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/sources.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/fetch.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/dates.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/summary.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/filters.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/routing.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/extract.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/weather.py",
    PROJECT_ROOT / "src/news_digest/pipeline/collector/fallbacks.py",
    PROJECT_ROOT / "src/news_digest/pipeline/dedupe.py",
    PROJECT_ROOT / "src/news_digest/pipeline/candidate_validator.py",
    PROJECT_ROOT / "src/news_digest/pipeline/writer.py",
    PROJECT_ROOT / "src/news_digest/pipeline/editor.py",
    PROJECT_ROOT / "src/news_digest/pipeline/release.py",
    PROJECT_ROOT / "src/news_digest/pipeline/history.py",
    PROJECT_ROOT / "src/news_digest/pipeline/common.py",
    PROJECT_ROOT / "src/news_digest/pipeline/config.py",
    PROJECT_ROOT / "src/news_digest/pipeline/fact_extraction.py",
    PROJECT_ROOT / "src/news_digest/pipeline/fact_normalization.py",
    PROJECT_ROOT / "src/news_digest/pipeline/fact_rewrite.py",
    PROJECT_ROOT / "scripts/run_local_digest.py",
)

# Recognise top-level def/class/UPPERCASE_CONSTANT lines.
SYMBOL_RE = re.compile(
    r"^(?:def\s+(?P<func>[A-Za-z_][A-Za-z0-9_]*)|"
    r"class\s+(?P<cls>[A-Za-z_][A-Za-z0-9_]*)|"
    r"(?P<const>[A-Z][A-Z0-9_]+)\s*[:=])"
)

START_MARKER = "<!-- AUTOGENERATED:modules:start -->"
END_MARKER = "<!-- AUTOGENERATED:modules:end -->"


def collect_symbols(path: Path) -> dict[str, list[str]]:
    """Return {kind: [names]} for a Python source file.

    Skips obviously-private locals (functions starting with `__`) and
    names already-private constants are surfaced without their leading
    underscore stripped — they help an agent know they exist.
    """

    buckets: dict[str, list[str]] = {"class": [], "def": [], "const": []}
    if not path.exists():
        return buckets
    for line in path.read_text(encoding="utf-8").splitlines():
        match = SYMBOL_RE.match(line)
        if not match:
            continue
        if match.group("cls"):
            buckets["class"].append(match.group("cls"))
        elif match.group("func"):
            name = match.group("func")
            if name.startswith("_"):  # skip private helpers (single and double underscore)
                continue
            buckets["def"].append(name)
        elif match.group("const"):
            buckets["const"].append(match.group("const"))
    return buckets


def render_module_map() -> str:
    """Build the markdown that sits between the AUTOGENERATED markers."""

    lines: list[str] = []
    for path in PIPELINE_FILES:
        rel = path.relative_to(PROJECT_ROOT)
        symbols = collect_symbols(path)
        if not any(symbols.values()):
            continue
        lines.append(f"### `{rel.as_posix()}`")
        lines.append("")
        if symbols["class"]:
            lines.append(f"- classes: `{'`, `'.join(symbols['class'])}`")
        if symbols["def"]:
            # Emit all public defs on one line (private helpers already filtered).
            lines.append(f"- defs: `{'`, `'.join(symbols['def'])}`")
        if not symbols["class"] and not symbols["def"]:
            lines.append("- all helpers private — use `rg -n '^def '`")
        if symbols["const"]:
            lines.append(f"- constants: `{'`, `'.join(symbols['const'])}`")
        lines.append("")
    lines.append(
        "_Anchors above are stable symbol names. "
        "Use `rg -n '^def NAME|^class NAME|^NAME ?='` to jump there._"
    )
    return "\n".join(lines)


def update_agents_md(new_block: str) -> tuple[str, str]:
    """Return (old_text, new_text). Caller decides whether to write."""

    text = AGENTS_MD.read_text(encoding="utf-8")
    if START_MARKER not in text or END_MARKER not in text:
        raise SystemExit(
            f"Markers {START_MARKER!r} / {END_MARKER!r} missing from AGENTS.md"
        )
    pattern = re.compile(
        rf"({re.escape(START_MARKER)})(.*?)({re.escape(END_MARKER)})",
        re.DOTALL,
    )
    replacement = f"{START_MARKER}\n{new_block}\n{END_MARKER}"
    new_text = pattern.sub(replacement, text, count=1)
    return text, new_text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if AGENTS.md is out of date instead of rewriting.",
    )
    args = parser.parse_args()

    block = render_module_map()
    old_text, new_text = update_agents_md(block)

    if args.check:
        if old_text != new_text:
            print("AGENTS.md is out of date. Run scripts/refresh_agents_md.py.")
            return 1
        print("AGENTS.md is up to date.")
        return 0

    if old_text == new_text:
        print("AGENTS.md already up to date.")
        return 0
    AGENTS_MD.write_text(new_text, encoding="utf-8")
    print(f"Refreshed AGENTS.md module map ({len(PIPELINE_FILES)} files indexed).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
